---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fRisbee

<!-- badges: start -->
<!-- badges: end -->

The goal of fRisbee is to ...

## Installation

You can install the released version of fRisbee from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("fRisbee")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("bbwieland/fRisbee")
```
## Example: Evaluating AUDL team performance

This is a basic example which shows you how to solve a common problem:

```{r}
library(fRisbee)

team_stats = fRisbee::load_audl_team_stats(season = 2022, stat_type = "game")
str(team_stats)
```

```{r}
library(dplyr)

# creating a 'net rating' variable:

team_stats = team_stats %>%
  dplyr::mutate(netRating = scoresFor - scoresAgainst)

# attaching the dataframe of team logos, glossary_AUDL_teams

team_stats = team_stats %>%
  dplyr::left_join(fRisbee::glossary_AUDL_teams, by = "teamName")

```

```{r}
library(ggplot2)

ggplot2::ggplot(team_stats, aes(x = netRating, y= reorder(teamName, netRating))) +
  geom_col() +
  labs(x = "Net Rating", y = "Team",
       title = "AUDL Net Ratings - 2022 Season") +
  theme_bw()
```

```{r}
library(ggimage)

ggplot2::ggplot(team_stats, aes(x = scoresFor, y = scoresAgainst)) +
  geom_image(aes(image = logoURL), asp = 1)
```

